version: '3.8'

services:
  # 1. Database MySQL
  mysql:
    image: mysql:8.0
    container_name: collab-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: collab_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. RabbitMQ (message broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: collab-rabbitmq
    ports:
      - "5672:5672"    # Port cho application kết nối
      - "15672:15672"  # Port cho RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
 
 # 3. Resource Service (Quản lý tài nguyên)
  resource-service:
    build:
      context: ./services/resource-service
    container_name: resource-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker


