version: '3.8'

services:
  # 1. Database MySQL
  mysql:
    image: mysql:8.0
    container_name: collab-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: collab_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. RabbitMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: collab-rabbitmq
    ports:
      - "5672:5672"    # Port cho application kết nối
      - "15672:15672"  # Port cho RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # 3. MinIO (Giả lập AWS S3 - MỚI THÊM)
  minio:
    image: minio/minio
    container_name: collab-minio
    ports:
      - "9000:9000"  # Cổng API (Code Java gọi vào đây)
      - "9001:9001"  # Cổng Web UI (Bạn vào đây để tạo Bucket)
    environment:
      MINIO_ROOT_USER: admin           # Access Key
      MINIO_ROOT_PASSWORD: password123 # Secret Key
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data # Lưu dữ liệu upload ra ổ cứng

volumes:
  mysql_data:
  minio_data: # Volume mới cho MinIO
 # 3. Resource Service (Quản lý tài nguyên)
  # resource-service:
  #   build:
  #     context: ./services/resource-service
  #   container_name: resource-service
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker


  # api-gateway:
  #   build: ./api-gateway
  #   container_name: api-gateway
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - evaluation-service

  # evaluation-service:
  #   build: ./services/evaluation-service
  #   container_name: evaluation-service
  #   ports:
  #     - "8083:8083"

