server:
  port: 8086 # Chạy trên cổng 8081 để tránh đụng độ

spring:
  application:
    name: identity-service

  datasource:
    # Kết nối đến MySQL đang chạy trong Docker (hoặc Local)
    url: jdbc:mysql://localhost:3307/identity_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Tự động tạo bảng khi chạy code (chỉ dùng cho Dev)
    show-sql: true # Hiện câu lệnh SQL để debug cho dễ
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
jwt:
  signerKey: 1234567890123456789012345678901212345678901234567890123456789012
