spring:
  application:
    name: resource-service # 1. Đặt lại tên chuẩn

  datasource:
    # 2. Đổi sang MySQL
    url: jdbc:mysql://localhost:3306/Resource_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # 3. Đổi Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8088 # 4. Đổi sang 8084 (theo quy hoạch)
  servlet:
    context-path: /api/resources

logging:
  level:
    root: INFO
    com.collab: DEBUG
