spring:
  application:
    name: resource-service

  # --- PHẦN MỚI THÊM ĐỂ SỬA LỖI REGION ---
  cloud:
    aws:
      region:
        static: us-east-1  # <--- Dòng này giúp fix lỗi "Unable to load region"
      credentials:
        access-key: admin
        secret-key: password123
  # ---------------------------------------

  datasource:
    url: jdbc:mysql://localhost:3306/collab_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8084


# Cấu hình Custom cho Code của bạn (Vẫn giữ nguyên để Service chạy)
aws:
  s3:
    access-key: admin
    secret-key: password123
    region: us-east-1
    bucket-name: collab-sphere
    endpoint: http://localhost:9000