global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "workspace-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "communication-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: "evaluation-service"
    metrics_path: "/api/evaluations/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8083"]

  - job_name: "class-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8084"]

  - job_name: "subject-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8085"]

  - job_name: "auth-identity-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8086"]

  - job_name: "ai-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8087"]

  - job_name: "resource-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8088"]

  - job_name: "project-service"
    metrics_path: "/api/v1/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8089"]

  - job_name: "collaboration-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8090"]

  - job_name: "team-service"
    metrics_path: "/api/v1/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8091"]

  - job_name: "notification-service"
    metrics_path: "/api/notifications/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8092"]
