spring:
  application:
    name: subject-service # 1. Đặt lại tên

  datasource:
    # 2. Đổi sang MySQL
    url: jdbc:mysql://localhost:3306/Subject_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # 3. Đổi Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8085 # 4. Đổi cổng sang 8085 (cho khỏi trùng)
  servlet:
    context-path: /api/subjects

logging:
  level:
    root: INFO
    com.collab: DEBUG
