spring:
  application:
<<<<<<< HEAD
    name: SERVICE_NAME_PLACEHOLDER
=======
    name: collaboration-service

>>>>>>> main
  profiles:
    active: dev

  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432/collab_db}
=======
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DB:collab_db}
>>>>>>> main
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
<<<<<<< HEAD
=======
    open-in-view: false
>>>>>>> main
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /
<<<<<<< HEAD
    connection-timeout: 10000ms
=======
    connection-timeout: 10000
>>>>>>> main

server:
  port: 8081
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
<<<<<<< HEAD
    "[com.collab]": DEBUG
=======
    com.collab: DEBUG
>>>>>>> main
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
