spring:
  application:
    name: notification-service

  # ======================
  # DATABASE (H2 IN-MEMORY)
  # ======================
  datasource:
    url: jdbc:h2:mem:notification-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  # ======================
  # RABBITMQ
  # ======================
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /#

  # ======================
  # MAIL (GIỮ NGUYÊN)
  # ======================
  mail:
    host: sandbox.smtp.mailtrap.io    # <-- Host của Mailtrap
    port: 2525                        # <-- Port của Mailtrap
    username: ff5d78373b7490           # <-- Copy Username từ Mailtrap dán vào đây
    password: 9d398343111aab          # <-- Copy Password từ Mailtrap dán vào đây
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# ======================
# SERVER
# ======================
server:
  port: 8092
  servlet:
    context-path: /api/notifications

# ======================
# LOGGING
# ======================
logging:
  level:
    root: INFO
    com.collab.notificationservice: DEBUG
    org.springframework.amqp: INFO
    org.hibernate.SQL: DEBUG
