spring:
  application:
    name: notification-service

  # ======================
  # DATABASE (H2 IN-MEMORY)
  # ======================


  h2:
    console:
      enabled: true
      path: /h2-console

  # ======================
  # RABBITMQ
  # ======================
  rabbitmq:
    host: localhost       # Địa chỉ RabbitMQ (nếu chạy Docker/Local)
    port: 5672            # Cổng mặc định
    username: guest       # User mặc định
    password: guest       # Pass mặc định
    listener:
      simple:
        auto-startup: true # Tự động lắng nghe khi bật app
        missing-queues-fatal: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: Thanhhh2005@gmail.com
    password: sipc pxyw mcft dyfa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # ======================
  # MAIL (GIỮ NGUYÊN)
  # ======================
  # mail:
  #   host: sandbox.smtp.mailtrap.io    # <-- Host của Mailtrap
  #   port: 2525                        # <-- Port của Mailtrap
  #   username: ff5d78373b7490           # <-- Copy Username từ Mailtrap dán vào đây
  #   password: 9d398343111aab          # <-- Copy Password từ Mailtrap dán vào đây
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true
# ======================
# SERVER
# ======================
server:
  port: 8092
  servlet:
    context-path: /api/notifications

# ======================
# LOGGING
# ======================
logging:
  level:
    root: INFO
    com.collab.notificationservice: DEBUG
    org.springframework.amqp: INFO
    org.hibernate.SQL: DEBUG
