server:
  port: 8082 # Cổng này khác cổng 8081 của workspace nhé

spring:
  application:
    name: communication-service
  datasource:
    # Dùng chung database collab_db cho tiện, nó sẽ tự tạo bảng riêng
    url: jdbc:mysql://localhost:3306/Communication_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
