spring:
  application:
    name: class-service # 1. Đặt tên đúng cho service
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/Class_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  # RabbitMQ: Giữ lại config này (dù chưa dùng tới ngay)
  # rabbitmq:
  #   host: ${RABBITMQ_HOST:localhost}
  #   port: ${RABBITMQ_PORT:5672}
  #   username: ${RABBITMQ_USERNAME:guest}
  #   password: ${RABBITMQ_PASSWORD:guest}
  #   virtual-host: /
  #   connection-timeout: 10000ms


server:
  port: 8084 # 

logging:
  level:
    root: INFO
    com.collab: DEBUG
